version: "3.4"
services:
    vite_docker:
        image: node:lts
        container_name: vite_docker
        entrypoint: /bin/sh
        ports:
            - 9000:8000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
